apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asi-dashboard

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-init-configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

